### ISSUE TITLE
Page class clash with other plugins

### ISSUE THREAD

**Issue by beejay41** [labgua/twig_plugin#1]
An interesting plugin, thank you.

On first enabling the plugin, your class name Page clashed with the  Andrea Micheloni's sitemap plugin.
Page is a popular name in this context.
I solved it by adding `namespace Gustaferro` to twig_plugin.php and  PageModel.class.php, then calling Gustaferro\render() in template.php.

**Comment by labgua** [comment]
Hi, 
Sorry for my absence.

It is a pleasure for me to receive issues from people but unfortunately this project was born in a period of programming inexperience while I was studying the Symfony framework for the first time. So it started out as a programming exercise.
I had no idea how important it could become for the GetSimple community.
So I decided to try again, in this quarantine period, and try to make it more dynamic.

Thank You for your advice: I didn't have and I don't have experience in the usage of GetSimple plugins...
It will be a pleasure for me to try to integrate it in a new version, but I will need your help! :smiley: 

Best regards,
Sergio Guastaferro

**Comment by beejay41** [comment]
Happy to assist in any way I can, but spurred on by the idea of twig, I have migrated my sites to another CMS called Grav, which I am finding superior to GetSimple and is built with twig at its core.
Regards,
Brian

**Comment by labgua** [comment]
As described by @beejay41 this problem has been solved by using namespace "Labgua\Twig_Plugin" in the Page class in the last commits
