### ISSUE TITLE
How to include queued css and js

### ISSUE THREAD

**Issue by beejay41** [labgua/twig_plugin#2]
Is there a way to include CSS and JS inserted by other plugins using queue_style|script() in a TWIG way, rather than still including `<?php get_header(TRUE); ?>` and `<?php get_footer(); ?>` in the theme somewhere?
It's a similar issue to components, but can't be evaluated until all the plugins have processed, particularly when a content plugin adds JS intended for footer inclusion.

**Comment by labgua** [comment]
Analyzing the doc I forgot to include the contents of the `get_header` and `get_footer` functions, now they are included in the base.html.twig template.
Given the multiple ways to create plugins, the solution was to directly create a wrap of php functions within a twig function called `_gs`
